config/routes.rb
Rails.application.routes.draw do
  resources :device_tokens
  resources :chats
  resources :messages
  resources :notifications
  resources :reports
  resources :comments
  resources :favorites
  resources :events
  resources :news
  resources :requests
  resources :communities
  resources :users
  resources :community_members
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace 'api' do
    post 'users/login', to: 'users#login'
    post 'users/register', to: 'users#register'
    put 'users/logout', to: 'users#logout'
    put 'users/edit', to: 'users#edit'
    put 'users/update_image', to: 'users#update_image'
    get 'users/get_users', to: 'users#get_users'
    post 'communities/create', to: 'communities#create'
    post 'communities/create_x_comm', to: 'communities#create_x_comm'
    get 'communities/get_communities', to: 'communities#get_communities'
    get 'communities/get_all_communities', to: 'communities#get_all_communities'
    get 'communities/search_community', to: 'communities#search_community'
    get 'communities/get_members', to: 'communities#get_members'
    put 'communities/edit', to: 'communities#edit'
    put 'communities/edit_x_comm', to: 'communities#edit_x_comm'
    delete 'communities/delete_x_comm', to: 'communities#delete_x_comm'
    get 'requests/get', to: 'requests#get'
    post 'requests/create', to: 'requests#create'
    post 'requests/accept', to: 'requests#accept'
    #put 'requests/put_seens', to: 'requests#put_seens'
    delete 'requests/delete', to: 'requests#delete'
    get 'requests/count_new_requests', to: 'requests#count_new_requests'
    post 'news/create', to: 'news#create'
    get 'news/get_news', to: 'news#get_news'
    get 'news/get_news_status', to: 'news#get_news_status'
    put 'news/approve_news', to: 'news#approve_news'
    put 'news/edit', to: 'news#edit'
    post 'events/create', to: 'events#create'
    get 'events/get_comm_events', to: 'events#get_comm_events'
    get 'events/get_user_events', to: 'events#get_user_events'
    delete 'news/delete_news', to: 'news#delete_news'
    post 'favorites/create', to: 'favorites#create'
    get 'favorites/get_newsFavorites', to: 'favorites#get_newsFavorites'
    delete 'favorites/delete_Favorites', to: 'favorites#delete_Favorites'
    post 'comments/create', to: 'comments#create'
    delete 'comments/delete_comments', to: 'comments#delete_comments'
    get 'comments/get_comments', to: 'comments#get_comments'
    put 'events/approve', to: 'events#approve'
    delete 'events/delete', to: 'events#delete'
    post 'reports/create', to: 'reports#create'
    get 'favorites/getListUsersCommunity_FavoriteNews', to: 'favorites#getListUsersCommunity_FavoriteNews'
    put 'notifications/put_seenNotification',  to: 'notifications#put_seenNotification'
    get 'notifications/get_newsNotifications', to: 'notifications#get_newsNotifications'
    delete 'notifications/delete_Notification', to: 'notifications#delete_Notification'
    get 'news/getSingleNews_by_id', to: 'news#getSingleNews_by_id'
    get 'events/getSingleEvent_by_id', to: 'events#getSingleEvent_by_id'
    post 'chats/send_message', to: 'chats#send_message'
    get 'chats/get_chats', to: 'chats#get_chats'
    get 'chats/get_messages', to: 'chats#get_messages'
    get 'notifications/getReportAndComment', to: 'notifications#getReportAndComment'
    delete 'community_members/delete', to: 'community_members#delete'

  end
end

app/models/notification.rb
class Notification < ApplicationRecord
end

app/controllers/api/notifications_controller.rb
module Api
    class NotificationsController < ApplicationController
      protect_from_forgery with: :null_session

        
        #PUT seen notification 
        #params auth_token, idNotification, idUser
        def put_seenNotification
            user = User.where(id: params[:idUser]).first
            token = params[:auth_token]
            if(user.auth_token == token)
                req = Notification.where(id: params[:idNotification]).first
                req.update(:seen=>true)


                render json: { status: 'SUCCESS', message: 'Notificacion actualizada' }, status: :ok
            else
                render json: { status: 'INVALID', message: 'Token invalido'}, status: :unauthorized
            end
        end
        
        
        #GET notifications by user
        #params auth_token, idUser
        def get_newsNotifications
            user = User.where(id: params[:idUser]).first
            token = params[:auth_token]
            if (user && user.auth_token == token)
              notifs = Notification.where(idUser: params[:idUser])
   
              #---------- Change authentication token ----------
              user.auth_token = nil
              o = [('a'..'z'), ('A'..'Z'), ('0'..'9')].map(&:to_a).flatten
              user.auth_token = (0...20).map { o[rand(o.length)] }.join
              user.save
              #--------------------------------------------------
      
              render json: { status: 'SUCCESS', message: 'Notificaciones obtenidas', auth_token: user.auth_token, notifications: notifs}, status: :ok
            else
              render json: { status: 'INVALID', message: 'Token invalido'}, status: :unauthorized
            end
        end
        
        
        #DELETE notifications by id
        #params idNotification 
        def delete_Notification
            dest = Notification.where(id: params[:idNotification]).first
            if (dest)   
                Notification.where(id: params[:idNotification]).destroy_all
                render json: { status: 'SUCCESS', message: 'ELIMINACION EXITOSA'}, status: :ok
            else
                render json: { status: 'INVALID', message: 'NOTIFICACION NO ENCONTRADA'}, status: :unauthorized
            end
        end

        #GET report and comment bi idReport
        #params auth_token, idUser, idReport
        def getReportAndComment
            user = User.where(id: params[:idUser]).first
            token = params[:auth_token]
            if (user && user.auth_token == token)
   
              #---------- Change authentication token ----------
              user.auth_token = nil
              o = [('a'..'z'), ('A'..'Z'), ('0'..'9')].map(&:to_a).flatten
              user.auth_token = (0...20).map { o[rand(o.length)] }.join
              user.save
              #--------------------------------------------------

              r = Report.where(id: params[:idReport]).first      #return
              c = Comment.where(id: r.id_comment).first          #return
              news = New.where(id: c.id_news).first
              tNews = news.title                             #return
              community = Community.where(id: news.idCommunity).first
              nCommunity = community.name
              usr = User.where(id: c.id_user).first
              nUser = usr.name



      
              render json: { status: 'SUCCESS', message: 'Reporte obtenido', auth_token: user.auth_token, report: r, comment: c, titleNews: tNews, nameCommunity: nCommunity, nameUser: nUser}, status: :ok
            else
              render json: { status: 'INVALID', message: 'Token invalido'}, status: :unauthorized
            end
        end
          
    end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.all
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url, notice: 'Notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:idUser, :idContent, :created_at, :isNews, :isReports, :isEvents, :titleContent, :seen)
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_for(notification) do |f| %>
  <% if notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :idUser %>
    <%= f.number_field :idUser %>
  </div>

  <div class="field">
    <%= f.label :idContent %>
    <%= f.number_field :idContent %>
  </div>

  <div class="field">
    <%= f.label :created_at %>
    <%= f.datetime_select :created_at %>
  </div>

  <div class="field">
    <%= f.label :isNews %>
    <%= f.check_box :isNews %>
  </div>

  <div class="field">
    <%= f.label :isReports %>
    <%= f.check_box :isReports %>
  </div>

  <div class="field">
    <%= f.label :isEvents %>
    <%= f.check_box :isEvents %>
  </div>

  <div class="field">
    <%= f.label :titleContent %>
    <%= f.text_field :titleContent %>
  </div>

  <div class="field">
    <%= f.label :seen %>
    <%= f.check_box :seen %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notifications</h1>

<table>
  <thead>
    <tr>
      <th>Iduser</th>
      <th>Idcontent</th>
      <th>Created at</th>
      <th>Isnews</th>
      <th>Isreports</th>
      <th>Isevents</th>
      <th>Titlecontent</th>
      <th>Seen</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notifications.each do |notification| %>
      <tr>
        <td><%= notification.idUser %></td>
        <td><%= notification.idContent %></td>
        <td><%= notification.created_at %></td>
        <td><%= notification.isNews %></td>
        <td><%= notification.isReports %></td>
        <td><%= notification.isEvents %></td>
        <td><%= notification.titleContent %></td>
        <td><%= notification.seen %></td>
        <td><%= link_to 'Show', notification %></td>
        <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
        <td><%= link_to 'Destroy', notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notification', new_notification_path %>

app/views/notifications/new.html.erb
<h1>New Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Iduser:</strong>
  <%= @notification.idUser %>
</p>

<p>
  <strong>Idcontent:</strong>
  <%= @notification.idContent %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @notification.created_at %>
</p>

<p>
  <strong>Isnews:</strong>
  <%= @notification.isNews %>
</p>

<p>
  <strong>Isreports:</strong>
  <%= @notification.isReports %>
</p>

<p>
  <strong>Isevents:</strong>
  <%= @notification.isEvents %>
</p>

<p>
  <strong>Titlecontent:</strong>
  <%= @notification.titleContent %>
</p>

<p>
  <strong>Seen:</strong>
  <%= @notification.seen %>
</p>

<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>