config/routes.rb
Rails.application.routes.draw do
  resources :device_tokens
  resources :chats
  resources :messages
  resources :notifications
  resources :reports
  resources :comments
  resources :favorites
  resources :events
  resources :news
  resources :requests
  resources :communities
  resources :users
  resources :community_members
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace 'api' do
    post 'users/login', to: 'users#login'
    post 'users/register', to: 'users#register'
    put 'users/logout', to: 'users#logout'
    put 'users/edit', to: 'users#edit'
    put 'users/update_image', to: 'users#update_image'
    get 'users/get_users', to: 'users#get_users'
    post 'communities/create', to: 'communities#create'
    post 'communities/create_x_comm', to: 'communities#create_x_comm'
    get 'communities/get_communities', to: 'communities#get_communities'
    get 'communities/get_all_communities', to: 'communities#get_all_communities'
    get 'communities/search_community', to: 'communities#search_community'
    get 'communities/get_members', to: 'communities#get_members'
    put 'communities/edit', to: 'communities#edit'
    put 'communities/edit_x_comm', to: 'communities#edit_x_comm'
    delete 'communities/delete_x_comm', to: 'communities#delete_x_comm'
    get 'requests/get', to: 'requests#get'
    post 'requests/create', to: 'requests#create'
    post 'requests/accept', to: 'requests#accept'
    #put 'requests/put_seens', to: 'requests#put_seens'
    delete 'requests/delete', to: 'requests#delete'
    get 'requests/count_new_requests', to: 'requests#count_new_requests'
    post 'news/create', to: 'news#create'
    get 'news/get_news', to: 'news#get_news'
    get 'news/get_news_status', to: 'news#get_news_status'
    put 'news/approve_news', to: 'news#approve_news'
    put 'news/edit', to: 'news#edit'
    post 'events/create', to: 'events#create'
    get 'events/get_comm_events', to: 'events#get_comm_events'
    get 'events/get_user_events', to: 'events#get_user_events'
    delete 'news/delete_news', to: 'news#delete_news'
    post 'favorites/create', to: 'favorites#create'
    get 'favorites/get_newsFavorites', to: 'favorites#get_newsFavorites'
    delete 'favorites/delete_Favorites', to: 'favorites#delete_Favorites'
    post 'comments/create', to: 'comments#create'
    delete 'comments/delete_comments', to: 'comments#delete_comments'
    get 'comments/get_comments', to: 'comments#get_comments'
    put 'events/approve', to: 'events#approve'
    delete 'events/delete', to: 'events#delete'
    post 'reports/create', to: 'reports#create'
    get 'favorites/getListUsersCommunity_FavoriteNews', to: 'favorites#getListUsersCommunity_FavoriteNews'
    put 'notifications/put_seenNotification',  to: 'notifications#put_seenNotification'
    get 'notifications/get_newsNotifications', to: 'notifications#get_newsNotifications'
    delete 'notifications/delete_Notification', to: 'notifications#delete_Notification'
    get 'news/getSingleNews_by_id', to: 'news#getSingleNews_by_id'
    get 'events/getSingleEvent_by_id', to: 'events#getSingleEvent_by_id'
    post 'chats/send_message', to: 'chats#send_message'
    get 'chats/get_chats', to: 'chats#get_chats'
    get 'chats/get_messages', to: 'chats#get_messages'
    get 'notifications/getReportAndComment', to: 'notifications#getReportAndComment'
    delete 'community_members/delete', to: 'community_members#delete'

  end
end

app/models/chat.rb
class Chat < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/community.rb
class Community < ApplicationRecord
end

app/models/community_member.rb
class CommunityMember < ApplicationRecord
end

app/models/device_token.rb
class DeviceToken < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/new.rb
class New < ApplicationRecord
end

app/models/notification.rb
class Notification < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/request.rb
class Request < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/device_tokens_controller.rb
class DeviceTokensController < ApplicationController
  before_action :set_device_token, only: [:show, :edit, :update, :destroy]

  # GET /device_tokens
  # GET /device_tokens.json
  def index
    @device_tokens = DeviceToken.all
  end

  # GET /device_tokens/1
  # GET /device_tokens/1.json
  def show
  end

  # GET /device_tokens/new
  def new
    @device_token = DeviceToken.new
  end

  # GET /device_tokens/1/edit
  def edit
  end

  # POST /device_tokens
  # POST /device_tokens.json
  def create
    @device_token = DeviceToken.new(device_token_params)

    respond_to do |format|
      if @device_token.save
        format.html { redirect_to @device_token, notice: 'Device token was successfully created.' }
        format.json { render :show, status: :created, location: @device_token }
      else
        format.html { render :new }
        format.json { render json: @device_token.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /device_tokens/1
  # PATCH/PUT /device_tokens/1.json
  def update
    respond_to do |format|
      if @device_token.update(device_token_params)
        format.html { redirect_to @device_token, notice: 'Device token was successfully updated.' }
        format.json { render :show, status: :ok, location: @device_token }
      else
        format.html { render :edit }
        format.json { render json: @device_token.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /device_tokens/1
  # DELETE /device_tokens/1.json
  def destroy
    @device_token.destroy
    respond_to do |format|
      format.html { redirect_to device_tokens_url, notice: 'Device token was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device_token
      @device_token = DeviceToken.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_token_params
      params.require(:device_token).permit(:id_user, :token)
    end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/device_tokens_helper.rb
module DeviceTokensHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/device_tokens/_form.html.erb
<%= form_for(device_token) do |f| %>
  <% if device_token.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(device_token.errors.count, "error") %> prohibited this device_token from being saved:</h2>

      <ul>
      <% device_token.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_user %>
    <%= f.number_field :id_user %>
  </div>

  <div class="field">
    <%= f.label :token %>
    <%= f.text_field :token %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/device_tokens/edit.html.erb
<h1>Editing Device Token</h1>

<%= render 'form', device_token: @device_token %>

<%= link_to 'Show', @device_token %> |
<%= link_to 'Back', device_tokens_path %>

app/views/device_tokens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Device Tokens</h1>

<table>
  <thead>
    <tr>
      <th>Id user</th>
      <th>Token</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @device_tokens.each do |device_token| %>
      <tr>
        <td><%= device_token.id_user %></td>
        <td><%= device_token.token %></td>
        <td><%= link_to 'Show', device_token %></td>
        <td><%= link_to 'Edit', edit_device_token_path(device_token) %></td>
        <td><%= link_to 'Destroy', device_token, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Device Token', new_device_token_path %>

app/views/device_tokens/new.html.erb
<h1>New Device Token</h1>

<%= render 'form', device_token: @device_token %>

<%= link_to 'Back', device_tokens_path %>

app/views/device_tokens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id user:</strong>
  <%= @device_token.id_user %>
</p>

<p>
  <strong>Token:</strong>
  <%= @device_token.token %>
</p>

<%= link_to 'Edit', edit_device_token_path(@device_token) %> |
<%= link_to 'Back', device_tokens_path %>