config/routes.rb
Rails.application.routes.draw do
  resources :device_tokens
  resources :chats
  resources :messages
  resources :notifications
  resources :reports
  resources :comments
  resources :favorites
  resources :events
  resources :news
  resources :requests
  resources :communities
  resources :users
  resources :community_members
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace 'api' do
    post 'users/login', to: 'users#login'
    post 'users/register', to: 'users#register'
    put 'users/logout', to: 'users#logout'
    put 'users/edit', to: 'users#edit'
    put 'users/update_image', to: 'users#update_image'
    get 'users/get_users', to: 'users#get_users'
    post 'communities/create', to: 'communities#create'
    post 'communities/create_x_comm', to: 'communities#create_x_comm'
    get 'communities/get_communities', to: 'communities#get_communities'
    get 'communities/get_all_communities', to: 'communities#get_all_communities'
    get 'communities/search_community', to: 'communities#search_community'
    get 'communities/get_members', to: 'communities#get_members'
    put 'communities/edit', to: 'communities#edit'
    put 'communities/edit_x_comm', to: 'communities#edit_x_comm'
    delete 'communities/delete_x_comm', to: 'communities#delete_x_comm'
    get 'requests/get', to: 'requests#get'
    post 'requests/create', to: 'requests#create'
    post 'requests/accept', to: 'requests#accept'
    #put 'requests/put_seens', to: 'requests#put_seens'
    delete 'requests/delete', to: 'requests#delete'
    get 'requests/count_new_requests', to: 'requests#count_new_requests'
    post 'news/create', to: 'news#create'
    get 'news/get_news', to: 'news#get_news'
    get 'news/get_news_status', to: 'news#get_news_status'
    put 'news/approve_news', to: 'news#approve_news'
    put 'news/edit', to: 'news#edit'
    post 'events/create', to: 'events#create'
    get 'events/get_comm_events', to: 'events#get_comm_events'
    get 'events/get_user_events', to: 'events#get_user_events'
    delete 'news/delete_news', to: 'news#delete_news'
    post 'favorites/create', to: 'favorites#create'
    get 'favorites/get_newsFavorites', to: 'favorites#get_newsFavorites'
    delete 'favorites/delete_Favorites', to: 'favorites#delete_Favorites'
    post 'comments/create', to: 'comments#create'
    delete 'comments/delete_comments', to: 'comments#delete_comments'
    get 'comments/get_comments', to: 'comments#get_comments'
    put 'events/approve', to: 'events#approve'
    delete 'events/delete', to: 'events#delete'
    post 'reports/create', to: 'reports#create'
    get 'favorites/getListUsersCommunity_FavoriteNews', to: 'favorites#getListUsersCommunity_FavoriteNews'
    put 'notifications/put_seenNotification',  to: 'notifications#put_seenNotification'
    get 'notifications/get_newsNotifications', to: 'notifications#get_newsNotifications'
    delete 'notifications/delete_Notification', to: 'notifications#delete_Notification'
    get 'news/getSingleNews_by_id', to: 'news#getSingleNews_by_id'
    get 'events/getSingleEvent_by_id', to: 'events#getSingleEvent_by_id'
    post 'chats/send_message', to: 'chats#send_message'
    get 'chats/get_chats', to: 'chats#get_chats'
    get 'chats/get_messages', to: 'chats#get_messages'
    get 'notifications/getReportAndComment', to: 'notifications#getReportAndComment'
    delete 'community_members/delete', to: 'community_members#delete'

  end
end

app/models/chat.rb
class Chat < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/community.rb
class Community < ApplicationRecord
end

app/models/community_member.rb
class CommunityMember < ApplicationRecord
end

app/models/device_token.rb
class DeviceToken < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/new.rb
class New < ApplicationRecord
end

app/models/notification.rb
class Notification < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/request.rb
class Request < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/api/community_members_controller.rb
module Api
    class CommunityMembersController < ApplicationController
      protect_from_forgery with: :null_session
      
     def delete
         
        cm = CommunityMember.where(id_community: params[:id_community]).where(id_user: params[:id_user]).first
        if (cm)
            
            CommunityMember.where(id_community: params[:id_community]).where(id_user: params[:id_user]).destroy_all
            render json: { status: 'SUCCESS', message: 'ELIMINACION EXITOSA'}, status: :ok
        else
            render json: { status: 'INVALID', message: 'NO ENCONTRADA'}, status: :unauthorized
            
        end
        
      end

    end
end

app/controllers/community_members_controller.rb
class CommunityMembersController < ApplicationController
  before_action :set_community_member, only: [:show, :edit, :update, :destroy]

  # GET /community_members
  # GET /community_members.json
  def index
    @community_members = CommunityMember.all
  end

  # GET /community_members/1
  # GET /community_members/1.json
  def show
  end

  # GET /community_members/new
  def new
    @community_member = CommunityMember.new
  end

  # GET /community_members/1/edit
  def edit
  end

  # POST /community_members
  # POST /community_members.json
  def create
    @community_member = CommunityMember.new(community_member_params)

    respond_to do |format|
      if @community_member.save
        format.html { redirect_to @community_member, notice: 'Community member was successfully created.' }
        format.json { render :show, status: :created, location: @community_member }
      else
        format.html { render :new }
        format.json { render json: @community_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /community_members/1
  # PATCH/PUT /community_members/1.json
  def update
    respond_to do |format|
      if @community_member.update(community_member_params)
        format.html { redirect_to @community_member, notice: 'Community member was successfully updated.' }
        format.json { render :show, status: :ok, location: @community_member }
      else
        format.html { render :edit }
        format.json { render json: @community_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /community_members/1
  # DELETE /community_members/1.json
  def destroy
    @community_member.destroy
    respond_to do |format|
      format.html { redirect_to community_members_url, notice: 'Community member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_community_member
      @community_member = CommunityMember.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def community_member_params
      params.require(:community_member).permit(:id_community, :id_user, :isAdmin)
    end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/community_members_helper.rb
module CommunityMembersHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/community_members/_form.html.erb
<%= form_for(community_member) do |f| %>
  <% if community_member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(community_member.errors.count, "error") %> prohibited this community_member from being saved:</h2>

      <ul>
      <% community_member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_community %>
    <%= f.number_field :id_community %>
  </div>

  <div class="field">
    <%= f.label :id_user %>
    <%= f.number_field :id_user %>
  </div>

  <div class="field">
    <%= f.label :isAdmin %>
    <%= f.check_box :isAdmin %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/community_members/edit.html.erb
<h1>Editing Community Member</h1>

<%= render 'form', community_member: @community_member %>

<%= link_to 'Show', @community_member %> |
<%= link_to 'Back', community_members_path %>

app/views/community_members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Community Members</h1>

<table>
  <thead>
    <tr>
      <th>Id community</th>
      <th>Id user</th>
      <th>Isadmin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @community_members.each do |community_member| %>
      <tr>
        <td><%= community_member.id_community %></td>
        <td><%= community_member.id_user %></td>
        <td><%= community_member.isAdmin %></td>
        <td><%= link_to 'Show', community_member %></td>
        <td><%= link_to 'Edit', edit_community_member_path(community_member) %></td>
        <td><%= link_to 'Destroy', community_member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Community Member', new_community_member_path %>

app/views/community_members/new.html.erb
<h1>New Community Member</h1>

<%= render 'form', community_member: @community_member %>

<%= link_to 'Back', community_members_path %>

app/views/community_members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id community:</strong>
  <%= @community_member.id_community %>
</p>

<p>
  <strong>Id user:</strong>
  <%= @community_member.id_user %>
</p>

<p>
  <strong>Isadmin:</strong>
  <%= @community_member.isAdmin %>
</p>

<%= link_to 'Edit', edit_community_member_path(@community_member) %> |
<%= link_to 'Back', community_members_path %>