config/routes.rb
Rails.application.routes.draw do
  resources :device_tokens
  resources :chats
  resources :messages
  resources :notifications
  resources :reports
  resources :comments
  resources :favorites
  resources :events
  resources :news
  resources :requests
  resources :communities
  resources :users
  resources :community_members
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace 'api' do
    post 'users/login', to: 'users#login'
    post 'users/register', to: 'users#register'
    put 'users/logout', to: 'users#logout'
    put 'users/edit', to: 'users#edit'
    put 'users/update_image', to: 'users#update_image'
    get 'users/get_users', to: 'users#get_users'
    post 'communities/create', to: 'communities#create'
    post 'communities/create_x_comm', to: 'communities#create_x_comm'
    get 'communities/get_communities', to: 'communities#get_communities'
    get 'communities/get_all_communities', to: 'communities#get_all_communities'
    get 'communities/search_community', to: 'communities#search_community'
    get 'communities/get_members', to: 'communities#get_members'
    put 'communities/edit', to: 'communities#edit'
    put 'communities/edit_x_comm', to: 'communities#edit_x_comm'
    delete 'communities/delete_x_comm', to: 'communities#delete_x_comm'
    get 'requests/get', to: 'requests#get'
    post 'requests/create', to: 'requests#create'
    post 'requests/accept', to: 'requests#accept'
    #put 'requests/put_seens', to: 'requests#put_seens'
    delete 'requests/delete', to: 'requests#delete'
    get 'requests/count_new_requests', to: 'requests#count_new_requests'
    post 'news/create', to: 'news#create'
    get 'news/get_news', to: 'news#get_news'
    get 'news/get_news_status', to: 'news#get_news_status'
    put 'news/approve_news', to: 'news#approve_news'
    put 'news/edit', to: 'news#edit'
    post 'events/create', to: 'events#create'
    get 'events/get_comm_events', to: 'events#get_comm_events'
    get 'events/get_user_events', to: 'events#get_user_events'
    delete 'news/delete_news', to: 'news#delete_news'
    post 'favorites/create', to: 'favorites#create'
    get 'favorites/get_newsFavorites', to: 'favorites#get_newsFavorites'
    delete 'favorites/delete_Favorites', to: 'favorites#delete_Favorites'
    post 'comments/create', to: 'comments#create'
    delete 'comments/delete_comments', to: 'comments#delete_comments'
    get 'comments/get_comments', to: 'comments#get_comments'
    put 'events/approve', to: 'events#approve'
    delete 'events/delete', to: 'events#delete'
    post 'reports/create', to: 'reports#create'
    get 'favorites/getListUsersCommunity_FavoriteNews', to: 'favorites#getListUsersCommunity_FavoriteNews'
    put 'notifications/put_seenNotification',  to: 'notifications#put_seenNotification'
    get 'notifications/get_newsNotifications', to: 'notifications#get_newsNotifications'
    delete 'notifications/delete_Notification', to: 'notifications#delete_Notification'
    get 'news/getSingleNews_by_id', to: 'news#getSingleNews_by_id'
    get 'events/getSingleEvent_by_id', to: 'events#getSingleEvent_by_id'
    post 'chats/send_message', to: 'chats#send_message'
    get 'chats/get_chats', to: 'chats#get_chats'
    get 'chats/get_messages', to: 'chats#get_messages'
    get 'notifications/getReportAndComment', to: 'notifications#getReportAndComment'
    delete 'community_members/delete', to: 'community_members#delete'

  end
end

app/models/chat.rb
class Chat < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/community.rb
class Community < ApplicationRecord
end

app/models/community_member.rb
class CommunityMember < ApplicationRecord
end

app/models/device_token.rb
class DeviceToken < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/new.rb
class New < ApplicationRecord
end

app/models/notification.rb
class Notification < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/request.rb
class Request < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/api/reports_controller.rb
module Api
    class ReportsController < ApplicationController
      protect_from_forgery with: :null_session

      def create
          
          report = Report.new(id_user: params[:idUser], id_comment: params[:idComment], reason: params[:reason])
          if (report.save)  

            #---------- Cambiar authentication token ----------
            #user.auth_token = nil
            #o = [('a'..'z'), ('A'..'Z'), ('0'..'9')].map(&:to_a).flatten
            #user.auth_token = (0...20).map { o[rand(o.length)] }.join
            #user.save
            #--------------------------------------------------

            #Notifications
            comment = Comment.where(id: params[:idComment]).first
            news = New.where(id: comment.id_news).first
            idCom = news.idCommunity
            
            members = CommunityMember.where(id_community: idCom)
            members.each do |item|
              if(item.isAdmin == true)
                notif = Notification.new(idUser: item.id_user, idContent: report.id, isNews: false, isReports: true, isEvents: false, titleContent:  news.title, seen: false, photo: "")
                notif.save
              end
            end

            render json: { status: 'SUCCESS', message: 'Reporte creado'}, status: :created
          else
            render json: { status: 'INVALID', message: 'Error al crear reporte'}, status: :unauthorized
          end
      
      end  

      

    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:id_comment, :id_user, :reason)
    end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/reports/_form.html.erb
<%= form_for(report) do |f| %>
  <% if report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_comment %>
    <%= f.number_field :id_comment %>
  </div>

  <div class="field">
    <%= f.label :id_user %>
    <%= f.number_field :id_user %>
  </div>

  <div class="field">
    <%= f.label :reason %>
    <%= f.text_field :reason %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reports</h1>

<table>
  <thead>
    <tr>
      <th>Id comment</th>
      <th>Id user</th>
      <th>Reason</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.id_comment %></td>
        <td><%= report.id_user %></td>
        <td><%= report.reason %></td>
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<h1>New Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id comment:</strong>
  <%= @report.id_comment %>
</p>

<p>
  <strong>Id user:</strong>
  <%= @report.id_user %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @report.reason %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>